"""
Model Evaluation & Validation Module.
Smart Utility Expense Prediction System - Python 3.13.
"""
import json
import pickle
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

from .config import MODELS_DIR, REPORTS_DIR, REPORTS_FIGURES, RANDOM_SEED
from .features import build_features, load_feature_columns
from .train import time_aware_split, train_models


def load_model_and_scaler():
    """Load saved best_model.pkl and scaler.pkl."""
    with open(MODELS_DIR / "best_model.pkl", "rb") as f:
        model = pickle.load(f)
    scaler = None
    if (MODELS_DIR / "scaler.pkl").exists():
        with open(MODELS_DIR / "scaler.pkl", "rb") as f:
            scaler = pickle.load(f)
    return model, scaler


def evaluate_model(
    model,
    scaler,
    df: pd.DataFrame,
    target_col: str = "total",
) -> dict:
    """Compute MAE, RMSE, R2 on test set."""
    df_feat = build_features(df, target_col=target_col)
    feat_cols = load_feature_columns()
    feat_cols = [c for c in feat_cols if c in df_feat.columns]

    X_train, y_train, X_test, y_test = time_aware_split(df_feat, target_col=target_col)
    X_test = X_test[feat_cols].fillna(0)

    if scaler is not None:
        X_test_s = scaler.transform(X_test)
    else:
        X_test_s = X_test.values

    y_pred = model.predict(X_test_s)
    return {
        "MAE": float(mean_absolute_error(y_test, y_pred)),
        "RMSE": float(np.sqrt(mean_squared_error(y_test, y_pred))),
        "R2": float(r2_score(y_test, y_pred)),
        "y_test": y_test.values,
        "y_pred": y_pred,
    }


def save_metrics(metrics: dict, path: Path | None = None) -> Path:
    """Save metrics to reports/metrics.json"""
    if path is None:
        path = REPORTS_DIR / "metrics.json"
    path.parent.mkdir(parents=True, exist_ok=True)
    out = {k: v for k, v in metrics.items() if k not in ("y_test", "y_pred")}
    path.write_text(json.dumps(out, indent=2), encoding="utf-8")
    return path


def residual_plot(y_test: np.ndarray, y_pred: np.ndarray, save_path: Path) -> None:
    """Create and save residual analysis plot."""
    residuals = y_test - y_pred
    fig, axes = plt.subplots(1, 2, figsize=(12, 5))

    axes[0].scatter(y_pred, residuals, alpha=0.7)
    axes[0].axhline(0, color="red", linestyle="--")
    axes[0].set_xlabel("Predicted")
    axes[0].set_ylabel("Residual")
    axes[0].set_title("Residual Plot")
    axes[0].grid(True, alpha=0.3)

    axes[1].scatter(y_test, y_pred, alpha=0.7)
    max_val = max(y_test.max(), y_pred.max())
    axes[1].plot([0, max_val], [0, max_val], "r--", label="Perfect")
    axes[1].set_xlabel("Actual")
    axes[1].set_ylabel("Predicted")
    axes[1].set_title("Predicted vs Actual")
    axes[1].legend()
    axes[1].grid(True, alpha=0.3)

    plt.tight_layout()
    plt.savefig(save_path, dpi=150, bbox_inches="tight")
    plt.close()


def model_comparison_csv(results: dict, path: Path | None = None) -> Path:
    """Save model comparison to CSV."""
    if path is None:
        path = REPORTS_DIR / "model_comparison.csv"
    rows = []
    for name, m in results.items():
        if isinstance(m, dict) and "MAE" in m:
            rows.append({
                "model": name,
                "MAE": m.get("MAE"),
                "RMSE": m.get("RMSE"),
                "R2": m.get("R2"),
                "CV_R2_mean": m.get("CV_R2_mean"),
                "CV_R2_std": m.get("CV_R2_std"),
            })
    pd.DataFrame(rows).to_csv(path, index=False)
    return path


def run_evaluation() -> dict:
    """
    Full evaluation pipeline: load model -> evaluate -> save metrics & figures.
    """
    from .config import DATA_PROCESSED

    df = pd.read_csv(DATA_PROCESSED / "cleaned.csv")
    if "month_parsed" not in df.columns and "month" in df.columns:
        df["month_parsed"] = pd.to_datetime(df["month"].astype(str)).dt.to_period("M")

    model, scaler = load_model_and_scaler()
    metrics = evaluate_model(model, scaler, df)

    REPORTS_FIGURES.mkdir(parents=True, exist_ok=True)
    save_metrics(metrics)
    residual_plot(
        metrics["y_test"],
        metrics["y_pred"],
        REPORTS_FIGURES / "residual_analysis.png",
    )

    # Model comparison: load from training if available
    comp_path = REPORTS_DIR / "model_comparison.csv"
    if comp_path.exists():
        pass  # Already generated by train.py
    else:
        train_out = train_models(df, target_col="total", use_scaling=True)
        model_comparison_csv(train_out["results"])

    print("Evaluation complete.")
    print(f"MAE: {metrics['MAE']:.2f}, RMSE: {metrics['RMSE']:.2f}, R2: {metrics['R2']:.4f}")
    return metrics


if __name__ == "__main__":
    run_evaluation()
